services:
  db:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - ./db:/docker-entrypoint-initdb.d

  udf:
    build: https://github.com/Crackvignoule/tradingview-udf-binance-node.git
    restart: always
    ports:
      - "9090:80"

  server:
    image: node:latest
    restart: always
    working_dir: /app
    volumes:
      - ./server:/app
      - ./client:/client
    command: bash -c "cd /client && npm install && npm run build && cd /app && npm install && npm start"
    ports:
      - "3000:3000"
      - "5000:5000"
      - "8888:8888"
    depends_on:
      - db
      - udf

  client:
    image: nginx:latest
    restart: always
    volumes:
      - ./client/build:/usr/share/nginx/html
      - ./client/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - server
