services:
  trading-db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: TradingSimBdd
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: server
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d